### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by CoolLord22** [ObelusPA/CreativeParkour#8]
Recently got this error in the console. Unsure what it means.

https://pastebin.com/Y35SZVHY

`[15:29:49 WARN]: java.util.zip.ZipException: Not in GZIP format
[15:29:49 WARN]:        at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
[15:29:49 WARN]:        at java.util.zip.GZIPInputStream.<init>(Unknown Source)
[15:29:49 WARN]:        at java.util.zip.GZIPInputStream.<init>(Unknown Source)
[15:29:49 WARN]:        at net.creativeparkour.CPRequest.run(CPRequest.java:194)
[15:29:49 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
[15:29:49 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[15:29:49 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[15:29:49 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[15:29:49 WARN]:        at java.lang.Thread.run(Unknown Source)`

**Comment by ObelusPA** [comment]
Does it still occur? Because the website was down this day and it is probably the reason. But I should prevent this type of error anyway.
